# Generated by Django 3.2.15 on 2022-11-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221116_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
    ]
